# One or more services can be defined under the top-level key: services.
services:
    # The name postgres is the name of the database service.
    # This arbitrary name becomes the hostname of the container.
    postgres:
        # The image to use to create the container.
        image: postgres:15-alpine
        # The command is passed as arguments to the ENTRYPOINT script. 
        command: "-c shared_buffers=256MB -c max_connections=200"
        # Instructs compose to restart the container if it shuts 
        # down unless the container is intentionally stopped.
        restart: unless-stopped
        # The volumes mounted by this service.
        volumes:
            - pg_data_volume:/var/lib/postgresql/data
        # The networks attached to the container.
        networks:
            - web_to_db
        # Environment variables used to configure the database. 
        environment:
            - POSTGRES_USER=web_user
            - POSTGRES_PASSWORD=az93kfLS
            - POSTGRES_DB=web_app

